package de.werwolf2303.javasetuptool.components;

import de.werwolf2303.javasetuptool.Setup;
import de.werwolf2303.javasetuptool.swingextensions.JImagePanel;

import javax.swing.*;
import java.awt.*;
import java.io.ByteArrayInputStream;
import java.util.HashMap;

/**
 * The component is the first thing the user sees when the setup opens.
 * <br> <img alt="HTMLComponent" src="./doc-files/WelcomeComponent.png" />
 */
public class WelcomeComponent implements Component {
    private JPanel contentPanel;
    private JEditorPane pane;
    private JImagePanel image;
    private JButton backButton;

    @Override
    public void makeVisible(JFrame frame, JButton custom1, JButton custom2, JButton nextButton, JButton previousButton, JButton cancelButton, HashMap<String, Object> storage) {
        contentPanel.setVisible(true);
        backButton = previousButton;
        backButton.setVisible(false);
    }

    @Override
    public void makeInvisible(JFrame frame, JButton custom1, JButton custom2, JButton nextButton, JButton previousButton, JButton cancelButton, HashMap<String, Object> storage) {
        contentPanel.setVisible(false);
    }

    @Override
    public void init(JFrame frame, int width, int height, HashMap<String, Object> setupVariables) {
        pane.setBackground(new Color(0, 0, 0, 0));
        pane.setEditable(false);
        pane.setContentType("text/html");
        pane.setText("<h2 style='text-align:left'>Welcome to the " + setupVariables.getOrDefault("programname", "N/A") + " Setup Wizard</h2><br><br><br><a style='text-align:left'>This will install " + setupVariables.getOrDefault("programname", "N/A") + " version " + setupVariables.getOrDefault("programversion", "N/A") + " on your computer.</a><br><br><a>Click next to continue, or cancel to exit Setup</a>");
        image.setBackground(new Color(0, 0, 0, 0));
        if (setupVariables.containsKey("programimage")) {
            image.setImage(new ByteArrayInputStream((byte[]) setupVariables.get("programimage")));
        } else {
            image.setImage(Setup.class.getResourceAsStream("/JSTBranding.png"));
        }
    }

    @Override
    public boolean onNext() {
        backButton.setVisible(true);
        return false;
    }

    @Override
    public boolean onPrevious() {
        return false;
    }

    @Override
    public void onCustom1() {

    }

    @Override
    public void onCustom2() {

    }

    @Override
    public JPanel getContainer() {
        return contentPanel;
    }

    void createUIComponents() {
        image = new JImagePanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * 
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout(0, 0));
        contentPanel.setAlignmentX(0.0f);
        contentPanel.setAlignmentY(0.0f);
        pane = new JEditorPane();
        pane.setAlignmentX(0.0f);
        pane.setAlignmentY(0.0f);
        pane.setContentType("text/html");
        pane.setMargin(new Insets(0, 7, 0, 0));
        contentPanel.add(pane, BorderLayout.CENTER);
        contentPanel.add(image, BorderLayout.WEST);
    }

    /**
     * 
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

}
